---
development:
  cloud_name: kwy031820
  api_key: '265942777455281'
  api_secret: Hep4MNZ9B6xvb5CVs6vqZg_9VcA
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: kwy031820
  api_key: '265942777455281'
  api_secret: Hep4MNZ9B6xvb5CVs6vqZg_9VcA
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: kwy031820
  api_key: '265942777455281'
  api_secret: Hep4MNZ9B6xvb5CVs6vqZg_9VcA
  enhance_image_tag: true
  static_file_support: false

